### ISSUE TITLE
Oracle "Anonymous Block" Error if Terminating / is missing

### ISSUE THREAD

**Issue by DanielAdeniji** [onecompiler/bugs#13]
Error: Command failed: timeout 7 sqlplus

``` SQL

SET SERVEROUTPUT ON;

DECLARE  

         tsCurrentAsDate              date;

         tsCurrentAsString            varchar2(100);
         
         strLog                       varchar2(100);

BEGIN



  tsCurrentAsDate := SYSDATE();
  
  tsCurrentAsString := TO_CHAR(systimestamp, 'YYYY-MM-DD');
  
  strLog := 'Hello World ' || ' ' || tsCurrentAsString;
  
  DBMS_OUTPUT.PUT_LINE(strLog);
  

END;

-- please un-comment ny removing "--" to remediate 
--/

```

Shared here

https://onecompiler.com/oracle/42q76s6qc

**Comment by karthikdivi** [comment]
@DanielAdeniji 
Can you use PL/SQL for this code? [https://onecompiler.com/plsql](https://onecompiler.com/plsql)

**Comment by DanielAdeniji** [comment]
@karthikdivi :-  

Yes, I can use PL/SQL.

Sorry, I did not notice that there is a delineation between Oracle and PL/SQL.

Oracle itself works.

I just have to uncomment the block termination.

In essence currently have "**--/**".

Whereas, should have "**/**".

I am a bit more concerned with the error message as I think it lacks guidance on how easily the error can be corrected.

Currently, the error reads "Command failed: timeout 7 sqlplus".

 For a beginner user, he or she may wonder.
 
 And, for the system, we can better protect and insulate against timeout.
 
 Thank you ever Kindly Karthik.

**Comment by karthikdivi** [comment]
@DanielAdeniji I see the confusion that you ran into. We have tried to make both queries and PL/SQL code work as one language but we faced issues doing that. 
If you do not add `/` in PL/SQL code it doesn't work, let's say we went ahead and add it wile running the code then it created issues for simple queries ( you can see the issue here https://onecompiler.com/oracle/42qhj9vje ) it duplicate the results. 

So the best solution we could find is splitting both so for PL/SQL code we automatically append the `/` but not for Oracle

**Comment by DanielAdeniji** [comment]
Karthik:-

Sorry, I am "Johnny come late".

Should have "Read the F Manual ( RTFM )".

Please close the ticket.

All the labor and joy of text and language parsers.
